version: "3.8"

services:
  database:
    build: ./postgres/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: newsappdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - newsappnetwork

  newsaggregator:
    build: ./
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/newsappdatabase
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: docker
    networks:
      - newsappnetwork

volumes:
  postgres-data:
networks:
  newsappnetwork:
